sys:
  auth:
    tokenHeaderName: auth-token
server:
  port: ${SERVER_PORT:6002}
spring:
  application:
    name: system
  web:
    allowedOriginPatterns:
      - http://localhost:**
      - http://demo.xhansky.cn/**
      - http://192.168.**
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/xh_admin?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: local123
      configuration:
        maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
  #  邮箱配置 todo 修改为自己的邮箱发送配置 password为邮箱授权码
  mail:
    host: smtp.qq.com
    username: 2483482026@qq.com
    password: 邮箱授权码
    emailFrom: 2483482026@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

xxl:
  job:
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://122.51.118.42:8088/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token

minio:
  endpoint: http://122.51.118.42:9000
  access-key: QEGiz63wnKckxgmvTwre
  secret-key: CoWs7QBrFjsEonoFjkOx9eQhZGfE74n9VlmVNMOM
  bucket: bucket1

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml

# 支付宝支付配置
alipay:
  appId: 9021000149648583
  sellerId: 2088721069739774
  #是否沙箱环境
  sandbox: true
  #本地测试用内网穿透，这个内网穿透地址，修改为自己的。上线修改为后端的接口地址即可
  notifyUrl: https://stirring-sweet-doberman.ngrok-free.app/api/ex/order/notify/order
  #支付成功后跳转地址,上线修改为上线任意地址
  returnUrl: http://localhost:5173/console/products
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCiGlMsuf2Joei0uC2lJLoi6wxDnp1y5AsvERF2VNb4vrPqJRCwC5jELl0IvRqY6jxM3MruS2bsxkIcsY4XhMFvLkxecOzPl72NH5jve6uX2Z6+gxvUCmyYjY2HfBaVwl88WNV/8O0/16rpDmC6j45ODvHgIK/mURe/JGlJ6hpLXkHA2R3vbqHUxbAqNcJG0GxKd+FkOsZwOIh5vx9pH2m4G7M2e3S3WzIkiJ9PF3jd0WF2ZYrvkC8RueOOeQQAYYG9me/s9xhI+4PbET9mCyaxlV66f2035RB9Mc05ccgL2VmUkAFqeal7vahBDSon/p7ONzy38Jzu0a4k/PQy3ANjAgMBAAECggEAWU8dohe6iviMJ/0NEN5COvi64gpifqkLTFwf/czSP2t53jebkRJikTtmAGmHXNY4cLR4jX83bp3wULS2L1jx5ZphcurOXbUhNr5A2TiOmnPIVPgQ/ercV9QtNIb2Pn4/UBU1U27el3zv6cUFH+P1qCXttujrYH4vEh0ycQmsgPbE/Y4aoLORpXIsKPd5AHiqDH+V04kPBShIwwTKP0cjLD7W2tqq7wnGNTwY0DpH7Y7jiA/YYsOSWxQo/p5z7tqlcERuMfUAenEt+ZNsmcEc4XD9+U3w5ifUFqEFvdPasBeu6hGDHQaHV0CO6L9eOa98K5BmLP3WAgWz85Opr7nm8QKBgQDeI4cPjH/Omb/167fSTqsq9O25Y+Wt1UQxeKIhaupiKZc4MkOpjz8JNWCHcSB96BxPz5XnvvmUkPC/dKtHnz3ACsWxz/o5pDIoaqWqgi12rc4kUa1u8XQSwg07VzdNDh4f164Ihu25O8HRRr65VkyVmo1Y2jPhyNg86gZUc9NtSwKBgQC60Acey0+hScj9baZ/7QQ7tBhSyfA+VHEeNgPkPAIeroPHJPaPROs8pPp9YUHmTsJtCuQyBXldBU8dJaQOg+74H069s+tKWGah7hadA5a9eY0//oqNdwKThN4pxH7lSQ2j3P9fke+NCJNo0VLzPXAOnHUbSxY4tPJx0ut4MfrrSQKBgQC1bx8pPABHppx7KAQD6e00MMjZ2xYFXWNNZNJHqSO2+XFhnOxW2YEK7GXjOirnq2U0asBtgDYpehiox4n9/bpZ2HKQQOaHney5xiF5msm3XU45q9yT+PJtP8G+7gVlElrYdzjWDh6sZHpxi+7LQglbR9ia8d3eVEUJu7tfzxqo8QKBgQCcwFdpKHHNxUroE6zE5M1Lh4dtWFLFCjfMgMhtJ0kkE40xebuFZe/49/nTYNtZ87ZCpwPpURyPyBelPmNVZrEK88IvfZuty1V7BHtnDo7at/akvuHlZ/n6bF+6Lk3H+K+AUrzZpWubLJn8NsBip6eyKug8mZmwxWw1xCSeu1lvOQKBgQCLLoKSB89l+LxEm3TV7w15sN/dT4jgVsXYZWM7EdTJuNKqM6El3PgSZpRyZQ/6FwTWk/YMlHeigF8cLbnpwUdqfJP8DWLZOWC8PBHNFFGl7/QLVP+f0WYFbDBLs7yQtus7gfJGmMseflt2l/mcpqrlqKFEm/ZphIByvuJ2ITprcw==
  ali-pay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6s2beb6sJbYPG3ADeg0uN/DoNKK2IHq1M4nZPvYstp/kCCv7K3PXZgyN3oc8UwridBAsX+HIF+BwmPoShEmKmcuemVszvVgxWZV7Nf0xyeCo1UJYKJ6eJ84Wdiemun3/jI/SHoYYrnn48/JAEk9SXdXDqI3BXHAeYSBPA4bVoB2cx9VVtjqQY+Hr7GIhXcw9ibkcVhCMgQJrKvBCkE7E+3aXS1IK7pkm8ZGumg57AebLOpL8lzz/JZcpy3uOyZQpQn4VeYfviuVTAxXs9bl6dnB4OM80SZ+/OpFzVyhFqEXoD5s4RqVBnYZ4E6DDgSR0RiG5Cq2wfRltDboJegxmCwIDAQAB