sys:
  auth:
    tokenHeaderName: auth-token
server:
  port: ${SERVER_PORT:6002}
spring:
  application:
    name: system
  web:
    allowedOriginPatterns:
      - http://localhost:**
      - http://demo.xhansky.cn/**
      - http://192.168.**
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/xh_admin?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: local123
      configuration:
        maximum-pool-size: 20
#    second:
#      url: jdbc:postgresql://localhost:5432/bms
#      username: postgres
#      password: 123456
#      configuration:
#        maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
  #  邮箱配置 todo 修改为自己的邮箱发送配置 password为邮箱授权码
  mail:
    host: smtp.qq.com
    username: 2483482026@qq.com
    password: 邮箱授权码
    emailFrom: 2483482026@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

xxl:
  job:
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://122.51.118.42:8088/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token

minio:
  endpoint: http://122.51.118.42:9000
  access-key: QEGiz63wnKckxgmvTwre
  secret-key: CoWs7QBrFjsEonoFjkOx9eQhZGfE74n9VlmVNMOM
  bucket: bucket1

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml

# 支付宝支付配置 todo
alipay:
  appId: 2019xxx41568
  sellerId: 20xxx90687
  #是否沙箱环境
  sandbox: false
  #本地测试用内网穿透，这个内网穿透地址，修改为自己的。上线修改为后端的接口地址即可
  notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
  #支付成功后跳转地址,上线修改为上线任意地址
  returnUrl: http://localhost:8000/account/center
  private-key: xxxxxxxxxx
  ali-pay-public-key: xxxxxxxxxxxxxxxx